--* LAASYY HẾT CAC CỘT CỦA BẢNG
select *
from GIAOVIEN
--CHỈ LẤY 1 VÀI CỘT, TẤT CẢ DÒNG
SELECT MAGV, HOTEN, LUONG
FROM GIAOVIEN
--LẤY CÓ ĐIỀU KIỆN
SELECT *
FROM GIAOVIEN
WHERE LUONG>500
--NHIU HON 2 DKIEN: PHEP LOGIC AND, OR, BETWEEN...
SELECT TOP 3 *
FROM GIAOVIEN
WHERE LUONG>500 AND PHAI = 'NAM'
ORDER BY LUONG DESC
--KET HOP FUNCTION TRÊN SELECT , WHERE
SELECT MAGV, HOTEN, YEAR(NGSINH) AS [nam SINH]
FROM GIAOVIEN
WHERE LUONG>500 AND( YEAR(GETDATE())-YEAR(NGSINH))>55 AND PHAI = N'NAM'
--XEP THU TU

SELECT MAGV, HOTEN, YEAR(NGSINH) AS [nam SINH]
FROM GIAOVIEN
WHERE LUONG>500 AND( YEAR(GETDATE())-YEAR(NGSINH))>55 AND PHAI = N'NAM'
ORDER BY [NAM SINH] DESC

SELECT SUM(LUONG)
FROM GIAOVIEN

SELECT *
FROM GIAOVIEN
WHERE DIACHI LIKE N'%TP%'