--Cho biết mã của các giáo viên có họ tên bắt đầu là “Nguyễn” và lương trên $2000 hoặc, giáo viên là trưởng
--bộ môn nhận chức sau năm 1995.
SELECT MAGV
FROM GIAOVIEN
WHERE HOTEN LIKE N'NGUYỄN%' AND LUONG>2000

--CHO BIET TAT CA GIAOVIEN KEM THONG TIN GV LAM TRUONG BM
SELECT *
FROM GIAOVIEN GV LEFT JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
WHERE (HOTEN LIKE N'NGUYỄN%' AND LUONG>2000) or (TRUONGBM IS NOT NULL AND YEAR(NGAYNHANCHUC) >1995)

--CHO BIET GV NAO LA TRUONG BM
SELECT MAGV
FROM GIAOVIEN GV, BOMON BM
WHERE GV.MAGV = BM.TRUONGBM

--TUONG DUONG :
SELECT MAGV
FROM GIAOVIEN GV INNER JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM


--CHO BIET GV THUOC BO MON NAO
SELECT *
FROM GIAOVIEN GV, BOMON BM
WHERE GV.MABM = BM.MABM

SELECT * FROM GIAOVIEN

--Cho biết tên những giáo viên khoa Công nghệ thông tin.
SELECT *
FROM (GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM)JOIN KHOA KH ON BM.MAKHOA = KH.MAKHOA
WHERE TENKHOA LIKE N'CÔNG NGHỆ THÔNG TIN'


--Q1. Cho biết họ tên và mức lương của các giáo viên nữ.
SELECT GV.HOTEN, GV.LUONG
FROM GIAOVIEN GV